apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-odkujfhc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-odkujfhc:2dfd81cdbdb43a3c1a03b0935650fd2427fe1c00@sha256:66979433d021a633b0adda0e3ef1b9900f319f4a42d3ca76b66024c687b6a5f6
        name: container-image  
